version: "3.7"

services:
  mysql:
    image: mysql:5.7.28
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - /var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
  # db:
  #   image: postgres:13-alpine
  #   container_name: database
  #   restart: always
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: my-weak-password
  #   volumes:
  #     - /var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgAdmin
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@nestjs.com
  #     PGADMIN_DEFAULT_PASSWORD: my-weak-password
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - /var/lib/pgadmin
  #   depends_on:
  #     - db
